// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtT0-Scr7t3lMDSSHrOCYU4_GWuJXE7j8',
    appId: '1:253722320651:web:b32217534cc588365e8c0e',
    messagingSenderId: '253722320651',
    projectId: 'face-scan-62a20',
    authDomain: 'face-scan-62a20.firebaseapp.com',
    storageBucket: 'face-scan-62a20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiHMROMZKrIf23l0aB-rsZPYeWeugN4IM',
    appId: '1:253722320651:android:83454e5535e5301c5e8c0e',
    messagingSenderId: '253722320651',
    projectId: 'face-scan-62a20',
    storageBucket: 'face-scan-62a20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3ajE0eFvFuF-yFOJPHSnuPNr8DFSEmMA',
    appId: '1:253722320651:ios:a93f138fcc6f5e695e8c0e',
    messagingSenderId: '253722320651',
    projectId: 'face-scan-62a20',
    storageBucket: 'face-scan-62a20.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3ajE0eFvFuF-yFOJPHSnuPNr8DFSEmMA',
    appId: '1:253722320651:ios:a93f138fcc6f5e695e8c0e',
    messagingSenderId: '253722320651',
    projectId: 'face-scan-62a20',
    storageBucket: 'face-scan-62a20.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtT0-Scr7t3lMDSSHrOCYU4_GWuJXE7j8',
    appId: '1:253722320651:web:12eb378d5e711f1c5e8c0e',
    messagingSenderId: '253722320651',
    projectId: 'face-scan-62a20',
    authDomain: 'face-scan-62a20.firebaseapp.com',
    storageBucket: 'face-scan-62a20.firebasestorage.app',
  );

}